# Generated by Django 3.2 on 2021-04-10 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Id', models.IntegerField(default=1)),
                ('EnquiryId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('PhoneNo', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('Expiry', models.DateTimeField(auto_now_add=True, null=True)),
                ('Query', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('Review', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiry',
            },
        ),
    ]
