# Generated by Django 3.2 on 2021-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0002_alter_enquiry_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Feedback',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
